### ISSUE TITLE
Vector table is not changed

### ISSUE THREAD

**Issue by diondokter** [tweedegolf/dis-bootloader#5]
We use the cortex m bootload function: https://github.com/tweedegolf/dis-bootloader/blob/4741e294239b370745c81ddd9afb08da6a9a7ba3/bootloader/src/main.rs#L371
But that doesn't change the vector table. We should do that.

**Comment by hdoordt** [comment]
Could you provide more detail as to what needs to be updated in the vector table?

**Comment by diondokter** [comment]
Basically, [this register](https://docs.rs/cortex-m/latest/cortex_m/peripheral/scb/struct.RegisterBlock.html#structfield.vtor) needs to be set to the vector table of the firmware.
Here's a discription: https://wiki.segger.com/Arm_Cortex-M_interrupts#VTOR_Vector_table_offset_register.
Luckily for us, the nordic flash starts at 0x00000000, so the address of the vector table should be the value of the offset register.
